<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Tic Tac Toe</title>
  <style>
    * {
      box-sizing: border-box;
    }
    body {
      font-family: Arial, sans-serif;
      background: #f0f4f8;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
    }
    .game-container {
      text-align: center;
    }
    h1 {
      margin-bottom: 20px;
    }
    .board {
      display: grid;
      grid-template-columns: repeat(3, 100px);
      gap: 10px;
      margin-bottom: 20px;
    }
    .cell {
      width: 100px;
      height: 100px;
      background-color: #fff;
      border: 2px solid #ccc;
      font-size: 2rem;
      font-weight: bold;
      cursor: pointer;
      display: flex;
      justify-content: center;
      align-items: center;
      transition: background 0.2s;
    }
    .cell:hover {
      background-color: #f1f1f1;
    }
    .status {
      font-size: 1.2rem;
      margin-bottom: 10px;
    }
    .reset-btn {
      padding: 10px 20px;
      font-size: 1rem;
      background-color: #007bff;
      color: white;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }
    .reset-btn:hover {
      background-color: #0056b3;
    }
  </style>
</head>
<body>
  <div class="game-container">
    <h1>Tic Tac Toe</h1>
    <div class="status" id="status">Player X's turn</div>
    <div class="board" id="board">
      <!-- Cells will be generated by JS -->
    </div>
    <button class="reset-btn" onclick="resetGame()">Reset Game</button>
  </div>

  <script>
    const board = document.getElementById("board");
    const statusText = document.getElementById("status");

    let currentPlayer = "X";
    let cells = Array(9).fill("");
    let gameActive = true;

    const winningCombos = [
      [0,1,2], [3,4,5], [6,7,8],  // Rows
      [0,3,6], [1,4,7], [2,5,8],  // Columns
      [0,4,8], [2,4,6]            // Diagonals
    ];

    function createBoard() {
      board.innerHTML = "";
      cells.forEach((value, index) => {
        const cell = document.createElement("div");
        cell.classList.add("cell");
        cell.dataset.index = index;
        cell.innerText = value;
        cell.addEventListener("click", handleClick);
        board.appendChild(cell);
      });
    }

    function handleClick(e) {
      const index = e.target.dataset.index;
      if (cells[index] !== "" || !gameActive) return;

      cells[index] = currentPlayer;
      e.target.innerText = currentPlayer;

      if (checkWinner()) {
        statusText.innerText = `Player ${currentPlayer} wins!`;
        gameActive = false;
        return;
      }

      if (cells.every(cell => cell !== "")) {
        statusText.innerText = "It's a draw!";
        gameActive = false;
        return;
      }

      currentPlayer = currentPlayer === "X" ? "O" : "X";
      statusText.innerText = `Player ${currentPlayer}'s turn`;
    }

    function checkWinner() {
      return winningCombos.some(combo => {
        const [a, b, c] = combo;
        return cells[a] && cells[a] === cells[b] && cells[b] === cells[c];
      });
    }

    function resetGame() {
      cells = Array(9).fill("");
      currentPlayer = "X";
      gameActive = true;
      statusText.innerText = `Player ${currentPlayer}'s turn`;
      createBoard();
    }

    // Initialize board
    createBoard();
  </script>
</body>
</html>
